version: '3'
services:
  sickchill:
    image: sickchill/sickchill:latest@sha256:656a9d25224ddb886116b992cf70e434513802a59fe8f18f6f94e0709a7b0aee
    ports:
     - "8081:8081"
    volumes:
     - ./data/data:/data
     - ./data/download:/downloads
     - ./data/tv:/tv
    restart: unless-stopped
    depends_on:
     - transmission
    links:
     - transmission

  transmission:
    build: ./docker-transmission
    ports:
     - "45555:45555"
     - "9091:9091"
    environment:
      USERNAME: username
      PASSWORD: password
    volumes:
     - ./data/download/watch:/watch
     - ./data/download/complete:/downloads
     - ./data/download/incomplete:/incomplete
     - ./transmission_config:/config
    restart: unless-stopped
